<?php
define('DB_SERVER', 'localhost');
define('DB_USERNAME', 'c19passx');
define('DB_PASSWORD', 'pass007');
define('DB_DATABASE', 'c19passx');
define('UEK_SALT', '2eb33ae32efa3844f53b9779dc5dd3555c8e681ea08262350834295db98262ac2e0ce3de139a246abd014f619d6b3503c0fad3b98dda05bbfd2b1e3415eb50ee');
define('ENABLE_MARKETPLACE_SUPPORT', false);
define('ENABLE_NEWSFLOW_OVERLAY', false);
define('ENABLE_APP_NEWS', false);
define('ENABLE_APPLICATION_EVENTS', true);
define('PERMISSIONS_MODEL', 'advanced');
define('DATE_FORM_HELPER_FORMAT_HOUR', '24');
define('DATE_APP_DATE_PICKER', 'dd-mm-yy');
define('DATE_APP_GENERIC_MDYT_FULL', 'j. F Y - G:i');
define('DATE_APP_GENERIC_MDYT', 'j-n-Y - G:i');
define('DATE_APP_GENERIC_MDY', 'j-n-Y');
define('DATE_APP_GENERIC_MDY_FULL', 'j. F Y');
define('DATE_APP_DATE_ATTRIBUTE_TYPE_T', 'G:i:s');
define('DATE_APP_GENERIC_T', 'G:i:s');
define('DATE_APP_GENERIC_TS', 'G:i:s');
define('UP_SINCE', '2014-05-12 14:57:31');
define('ENABLE_INTELLIGENT_SEARCH_HELP', false);
define('ENABLE_INTELLIGENT_SEARCH_MARKETPLACE', false);
define('WHITE_LABEL_APP_NAME', 'PasswordX');
define('WHITE_LABEL_LOGO_SRC', '/images/logo_menu.png');
define('CONCRETE5_ORG_URL', 'http://www.concrete5.org/');
define('RECOVER_ACCESS_URL', 'https://github.com/KramericaIndustries/PasswordX/wiki/Recover-Access-to-PasswordX');
define('GITHUB_REPO_URL', 'https://github.com/KramericaIndustries/PasswordX');
define('GITHUB_ISSUES_URL', 'https://github.com/KramericaIndustries/PasswordX/issues');
define('SUPPRESS_SSL_WARNING', false);
define('SUPPRESS_TWOFACTOR_WARNING', false);
