<?php
define('DB_SERVER', 'localhost');
define('DB_USERNAME', 'c19passx');
define('DB_PASSWORD', 'pass007');
define('DB_DATABASE', 'c19passx');
define('UEK_SALT', '6cc649329b4d22a9648c0cd18e1aeabc236bfeea43ec577642803b45876a9ab20151a8c9dad13a939abf274340c5e66f0c5de04b5ce518f38d4c9a488bb8bffe');
define('ENABLE_MARKETPLACE_SUPPORT', false);
define('ENABLE_NEWSFLOW_OVERLAY', false);
define('ENABLE_APP_NEWS', false);
define('ENABLE_APPLICATION_EVENTS', true);
define('PERMISSIONS_MODEL', 'advanced');
define('DATE_FORM_HELPER_FORMAT_HOUR', '24');
define('DATE_APP_DATE_PICKER', 'dd-mm-yy');
define('DATE_APP_GENERIC_MDYT_FULL', 'j. F Y - G:i');
define('DATE_APP_GENERIC_MDYT', 'j-n-Y - G:i');
define('DATE_APP_GENERIC_MDY', 'j-n-Y');
define('DATE_APP_GENERIC_MDY_FULL', 'j. F Y');
define('DATE_APP_DATE_ATTRIBUTE_TYPE_T', 'G:i:s');
define('DATE_APP_GENERIC_T', 'G:i:s');
define('DATE_APP_GENERIC_TS', 'G:i:s');
define('UP_SINCE', '2014-04-15 09:32:53');
define('ENABLE_INTELLIGENT_SEARCH_HELP', false);
define('ENABLE_INTELLIGENT_SEARCH_MARKETPLACE', false);
define('WHITE_LABEL_APP_NAME', 'PasswordX');
define('WHITE_LABEL_LOGO_SRC', '/images/logo_menu.png');
define('CONCRETE5_ORG_URL', 'http://www.concrete5.org/r/-/167051');
define('RECOVER_ACCESS_URL', 'http://www.google.com');
define('GITHUB_REPO_URL', 'http://www.github.com');
define('GITHUB_ISSUES_URL', 'http://www.github.com');
define('SUPPRESS_SSL_WARNING', false);
define('SUPPRESS_TWOFACTOR_WARNING', false);
